export const FETCH_INVOICE = 'FETCH_INVOICE';
export const FETCH_STATUS = 'FETCH_STATUS';
export const FETCH_PAYMENT_TERM= 'FETCH_PAYMENT_TERM';
export const FETCH_SUPPLIER= 'FETCH_SUPPLIER';
export const FETCH_DOCUMENT_INVOICE='FETCH_DOCUMENT_INVOICE';